---
$patch: delete
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hunt-ui-src
---
$patch: delete
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hunt-ui-bin
---
$patch: delete
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hunt-backend-src
---
$patch: delete
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hunt-ui
---
$patch: delete
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hunt-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunt-ui
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunt-backend
spec:
  replicas: 0
