apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hunt-backend
  namespace: pod-hunt
  labels:
    app: hunt-backend
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    importPolicy: {}
    referencePolicy:
      type: Source
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/ubi
    name: ubi8
    importPolicy: {}
    referencePolicy:
      type: Source
