apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: hunt-ui
  name: hunt-ui-src
  namespace: pod-hunt
spec:
  output:
    to:
      kind: ImageStreamTag
      name: hunt-ui:src
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/vrutkovs/DuckHunt-JS
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: hunt-ui:nodejs
    type: Source
  triggers:
  - type: ImageChange
  - type: ConfigChange
