apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: hunt-backend
  name: hunt-backend
  namespace: pod-hunt
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: hunt-backend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/vrutkovs/k8s-podhunt
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: hunt-backend:ubi8
    type: Docker
  triggers:
  - type: ConfigChange
